services:
  - type: web
    name: campusfix-api
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: CampusFix
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://campusfix-api.onrender.com
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: true
      - key: RUN_SEEDER
        value: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AIVEN_CA_CERT_BASE64
        sync: false
      - key: CAMPUSFIX_IMAGE_DRIVER
        value: cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
